# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uK1pZr5CCMqoaCLg-CVlL64hkC3_lqTb
"""

import streamlit as st
import tensorflow as tf
import cv2
from PIL import Image,ImageOps
import numpy as np

@st.cache(allow_output_mutation=True)

def main():
  img=Image.open('agriculture.png')
  st.set_page_config(page_title='Agricultural Pests Classification',
                     page_icon=img)

  def load_model():
    model=tf.keras.models.load_model('model_pest.hdf5')
    return model

  model=load_model()
  st.write("""# Agricultural Pest Classification""")
  file=st.file_uploader("Choose Pest photo from computer",type=["jpg","png"])


  def import_and_predict(image_data,model):
      size=(64,64)
      image=ImageOps.fit(image_data,size,Image.ANTIALIAS)
      img=np.asarray(image)
      img_reshape=img[np.newaxis,...]
      prediction=model.predict(img_reshape)
      return prediction

  if file is None:
      st.text("Please upload an image file")
  else:
      image=Image.open(file)
      st.image(image,use_column_width=True)
      prediction=import_and_predict(image,model)
      class_names=['earthworms', 'weevil', 'snail', 'bees', 'earwig', 'beetle',
                    'moth', 'grasshopper', 'slug', 'wasp', 'catterpillar', 'ants']
      string="OUTPUT : "+class_names[np.argmax(prediction)]
      st.success(string)

if __name__ == "__main__":
    main()